# Site settings
name: Chinmay Shewale
title: Chinmay Shewale | Backend Engineer
description: Backend engineer who is a bit lazy but loves building development tools to make my work easier and automate the workflow.
baseurl: ''
email: shewalechinmay54@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:shewalechinmay54@gmail.com
  - title: twitter
    url: https://twitter.com/chinma_yyy
  - title: github
    url: https://github.com/chinma-yyy
  - title: linkedin
    url: https://www.linkedin.com/in/chinma_yyy

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
